version: "3"

services:
  go-web-app:
    depends_on:
      - redis
    restart: always
    ports: 
      - 8080:8080
    build:
<<<<<<< HEAD
        dockerfile: Dockerfile
        context: .
=======
      dockerfile: Dockerfile
      context: .
    links:
      - redis
>>>>>>> e3f11e02e7c61b46a916cfb22c17be7fbe4c99e7
    environment:
      PORT: 8080
      URL_DB: redis
      REDIS_URL: redis://172.20.1.2:6379
    networks:
      testing_net:
        ipv4_address: 172.20.1.3
  redis:
    image: redis:alpine
<<<<<<< HEAD
    ports:
      - 6379:6379
    networks:
      testing_net:
        ipv4_address: 172.20.1.2
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
    

=======
>>>>>>> e3f11e02e7c61b46a916cfb22c17be7fbe4c99e7
